import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@nimbus-ds/styles/dist/index.css"; 
import "@nimbus-ds/styles";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" >
      <body>{children}</body>
    </html>
  );
}
